/* eslint-disable @typescript-eslint/no-misused-promises */
import { type NextPage } from "next";
import Head from "next/head";
import { Strategy } from "~/utils/tabnews";
import { api } from "~/utils/api";

const Home: NextPage = () => {
    const postsQuery = api.example.listPosts.useInfiniteQuery(
        { limit: 10, strategy: Strategy.NEW },
        {
            refetchOnMount: false,
            refetchOnWindowFocus: false,
            staleTime: Infinity,
            getNextPageParam: (prevPage) => prevPage.nextCursor,
        }
    );

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <ul>
                    {postsQuery.data?.pages.map((page) =>
                        page.posts.map((post) => (
                            <li key={post.id}>
                                <p>
                                    {post.title} - {post.owner_username}
                                </p>
                            </li>
                        ))
                    )}
                </ul>
                <button
                    className="rounded bg-blue-500 px-4 py-2 text-white transition-all duration-300 hover:bg-blue-600"
                    onClick={() => postsQuery.fetchNextPage()}
                >
                    {postsQuery.isFetchingNextPage
                        ? "Loading..."
                        : "Load next page"}
                </button>
            </main>
        </>
    );
};

export default Home;
