import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import { _Region } from "~/constants/regions";
import { formatWhiteSpacesToUrl } from "~/utils/formatWhiteSpace";

const Home: NextPage = () => {
    const [summonerName, setSummonerName] = useState("");
    const [region, setRegion] = useState("na");

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <h1>Summoner Name</h1>
                <input
                    type="search"
                    value={summonerName}
                    onChange={(e) => setSummonerName(e.currentTarget.value)}
                />
                <h2>Region</h2>
                <select
                    value={region}
                    onChange={(e) => setRegion(e.currentTarget.value)}
                >
                    {Object.keys(_Region).map((region) => (
                        <option key={region} value={region}>
                            {region.toUpperCase()}
                        </option>
                    ))}
                </select>
                <Link
                    href={`/${region}/${formatWhiteSpacesToUrl(summonerName)}`}
                >
                    Search
                </Link>
            </main>
        </>
    );
};

export default Home;
